name: Create Jira Ticket for Github Issue

on:
  issues:
    types: [opened]

jobs:
  issue-jira:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        id: create_jira
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
          summary: Github | Issue | ${{ github.event.repository.name }} | ${{ github.event.issue.title }}
          description: |
            *GitHub Issue:* ${{ github.event.issue.html_url }}
            
            *Description:*
            ${{ github.event.issue.body }}
          fields: "${{ secrets.ISSUES_JIRA_FIELDS }}"