name: Create JIRA ISSUE
on:
  pull_request:
    types: [opened]
jobs:
  security-jira:
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'snyk-bot' || contains(github.event.pull_request.head.ref, 'snyk-fix-')  || contains(github.event.pull_request.head.ref, 'snyk-upgrade-')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login into JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create a JIRA Issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
          summary: |
            Snyk | Vulnerability | ${{ github.event.repository.name }} | ${{ github.event.pull_request.title }}
          description: |
            PR: ${{ github.event.pull_request.html_url }}

          fields: "${{ secrets.JIRA_FIELDS }}"
      - name: Transition issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: ${{ secrets.JIRA_TRANSITION }}
