name: Create JIRA ISSUE
on:
  pull_request:
    types: [opened]
jobs:
  security:
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'snyk-bot' || contains(github.event.pull_request.head.ref, 'snyk-fix-')  || contains(github.event.pull_request.head.ref, 'snyk-upgrade-')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login into JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create a JIRA Issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
          summary: |
            ${{ github.event.pull_request.title }}
          description: |
            PR: ${{ github.event.pull_request.html_url }}

            ${{ github.event.pull_request.body }}
