name: Secrets Scan
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gittyleaks
        uses: gupy-io/gittyleaks-action@v0.1
